#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Create build directory..."
rm -rf build && mkdir build

echo "==> Run test and static analysis pipeline..."
composer run test-ci
composer run static-analysis-ci || true
